//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.ScheduledNotifications.Repositories
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net;
	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Apps.Sections.Sections;
	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Net.ManagerStore;
	using Skyline.DataMiner.Net.Messages;
	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.Net.SubscriptionFilters;
	using Skyline.DataMiner.SDM;
	using Skyline.DataMiner.Utils.ScheduledNotifications.Models;

	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	internal partial class TemplateDomRepository : IBulkRepository<Template>
	{
		private readonly IConnection connection;
		private readonly DomHelper helper;
		public TemplateDomRepository(IConnection connection)
		{
			this.connection = connection;
			this.helper = new DomHelper(connection.HandleMessages, Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.ModuleId);
		}

		public Template Create(Template createObject)
		{
			if (createObject is null)
			{
				throw new ArgumentNullException(nameof(createObject));
			}

			var instance = ToInstance(createObject);
			instance = helper.DomInstances.Create(instance);
			return FromInstance(instance);
		}

		public IReadOnlyCollection<Template> Create(IEnumerable<Template> createObjects)
		{
			if (createObjects is null || !createObjects.Any())
			{
				return Array.Empty<Template>();
			}

			// Check if some of the objects already exist
			var existing = new HashSet<string>();
			foreach (var batch in createObjects.Batch(500))
			{
				existing.UnionWith(Read(new ORFilterElement<Template>(batch.Select(obj => TemplateExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
			}

			// Create the remainder
			var successfulItems = new List<Template>();
			var failures = new Dictionary<string, Exception>();
			var objects = createObjects.Where(obj => !existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
			foreach (var batch in createObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					successfulItems.Add(FromInstance(success));
				}
			}

			// If everything went fine, return the successful creations
			if (!existing.Any() && !failures.Any())
			{
				return successfulItems;
			}

			// Otherwise, build and throw an exception
			var exceptionBuilder = new SdmBulkCrudException<Template>.Builder();
			foreach (var obj in createObjects)
			{
				if (existing.Contains(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, new SdmCrudException<Template>(obj, $"Could not create Template with guid: '{obj.Identifier}', it already exists."));
					continue;
				}

				if (failures.ContainsKey(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
					continue;
				}

				exceptionBuilder.AddSuccessful(obj);
			}

			throw exceptionBuilder.Build();
		}

		public IReadOnlyCollection<Template> CreateOrUpdate(IEnumerable<Template> items)
		{
			if (items is null || !items.Any())
			{
				return Array.Empty<Template>();
			}

			var successful = new List<Template>();
			var exceptionBuilder = new SdmBulkCrudException<Template>.Builder();
			var objects = items.ToDictionary(obj => obj.Identifier);
			foreach (var batch in items.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					var item = FromInstance(success);
					exceptionBuilder.AddSuccessful(item);
					successful.Add(item);
				}
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}

			return successful;
		}

		public long Count(FilterElement<Template> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			return helper.DomInstances.Count(domFilter);
		}

		public long Count(IQuery<Template> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return helper.DomInstances.Count(domQuery);
		}

		public IEnumerable<Template> Read(FilterElement<Template> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			var domFilter = TranslateFullFilter(filter);
			return Read(domFilter);
		}

		public IEnumerable<Template> Read(IQuery<Template> query)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			return Read(domQuery);
		}

		public IEnumerable<IPagedResult<Template>> ReadPaged(FilterElement<Template> filter)
		{
			return ReadPaged(filter, 500);
		}

		public IEnumerable<IPagedResult<Template>> ReadPaged(FilterElement<Template> filter, int pageSize)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(filter);
			var paging = ReadPaged(domFilter, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<Template>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public IEnumerable<IPagedResult<Template>> ReadPaged(IQuery<Template> query)
		{
			return ReadPaged(query, 500);
		}

		public IEnumerable<IPagedResult<Template>> ReadPaged(IQuery<Template> query, int pageSize)
		{
			if (query is null)
			{
				throw new ArgumentNullException(nameof(query));
			}

			if (pageSize <= 0)
			{
				throw new ArgumentOutOfRangeException(nameof(pageSize), "The page size must be 1 or higher");
			}

			var domFilter = TranslateFullFilter(query.Filter);
			var domOrder = TranslateFullOrderBy(query.Order);
			var domQuery = query.WithFilter(domFilter).WithOrder(domOrder);
			var paging = ReadPaged(domQuery, pageSize).GetEnumerator();
			var moveNext = paging.MoveNext();
			var i = 0;
			while (moveNext)
			{
				var page = paging.Current.ToList();
				moveNext = paging.MoveNext();
				var result = new PagedResult<Template>(page, i, pageSize, moveNext);
				yield return result;
				i++;
			}
		}

		public Template Update(Template updateObject)
		{
			if (updateObject is null)
			{
				throw new ArgumentNullException(nameof(updateObject));
			}

			var instance = ToInstance(updateObject);
			instance = helper.DomInstances.Update(instance);
			return FromInstance(instance);
		}

		public IReadOnlyCollection<Template> Update(IEnumerable<Template> updateObjects)
		{
			if (updateObjects is null || !updateObjects.Any())
			{
				return Array.Empty<Template>();
			}

			// Check if which objects already exist
			var existing = new HashSet<string>();
			foreach (var batch in updateObjects.Batch(500))
			{
				existing.UnionWith(Read(new ORFilterElement<Template>(batch.Select(obj => TemplateExposers.Identifier.Equal(obj.Identifier)).ToArray())).Select(obj => obj.Identifier));
			}

			// Update the existing objects
			var successfulItems = new List<Template>();
			var failures = new Dictionary<string, Exception>();
			var objects = updateObjects.Where(obj => existing.Contains(obj.Identifier)).ToDictionary(obj => obj.Identifier);
			foreach (var batch in updateObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryCreateOrUpdate(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					failures.Add(failure.Id.ToString(), new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulItems)
				{
					successfulItems.Add(FromInstance(success));
				}
			}

			// Check for failures and build exception if needed
			var exceptionBuilder = new SdmBulkCrudException<Template>.Builder();
			foreach (var obj in updateObjects)
			{
				if (!existing.Contains(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, new SdmCrudException<Template>(obj, "Could not update a non existing Template"));
					continue;
				}

				if (failures.ContainsKey(obj.Identifier))
				{
					exceptionBuilder.AddFailed(obj, failures[obj.Identifier]);
					continue;
				}

				exceptionBuilder.AddSuccessful(obj);
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}

			return successfulItems;
		}

		public void Delete(Template deleteObject)
		{
			if (deleteObject is null)
			{
				throw new ArgumentNullException(nameof(deleteObject));
			}

			var instance = ToInstance(deleteObject);
			helper.DomInstances.Delete(instance);
		}

		public void Delete(IEnumerable<Template> deleteObjects)
		{
			if (deleteObjects is null || !deleteObjects.Any())
			{
				return;
			}

			var exceptionBuilder = new SdmBulkCrudException<Template>.Builder();
			var objects = deleteObjects.ToDictionary(obj => obj.Identifier);
			foreach (var batch in deleteObjects.Select(ToInstance).Batch(helper.DomInstances.MaxAmountBulkOperation))
			{
				helper.DomInstances.TryDelete(batch.ToList(), out var result);
				foreach (var failure in result.UnsuccessfulIds)
				{
					exceptionBuilder.AddFailed(objects[failure.Id.ToString()], new CrudFailedException(result.TraceDataPerItem[failure]));
				}

				foreach (var success in result.SuccessfulIds)
				{
					exceptionBuilder.AddSuccessful(objects[success.Id.ToString()]);
				}
			}

			if (exceptionBuilder.HasFailure)
			{
				throw exceptionBuilder.Build();
			}
		}

		private IEnumerable<Template> Read(FilterElement<DomInstance> domFilter)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			var domInstances = helper.DomInstances.Read(domFilter);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<Template> Read(IQuery<DomInstance> domQuery)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var domInstances = helper.DomInstances.Read(domQuery);
			return domInstances.Select(FromInstance);
		}

		private IEnumerable<IEnumerable<Template>> ReadPaged(FilterElement<DomInstance> domFilter, int pageSize)
		{
			if (domFilter is null)
			{
				throw new ArgumentNullException(nameof(domFilter));
			}

			domFilter = domFilter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			var pagingHelper = helper.DomInstances.PreparePaging(domFilter, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private IEnumerable<IEnumerable<Template>> ReadPaged(IQuery<DomInstance> domQuery, int pageSize)
		{
			if (domQuery is null)
			{
				throw new ArgumentNullException(nameof(domQuery));
			}

			var domFilter = domQuery.Filter.AND(DomInstanceExposers.DomDefinitionId.Equal(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId.Id));
			domQuery = domQuery.WithFilter(domFilter);
			var pagingHelper = helper.DomInstances.PreparePaging(domQuery, pageSize);
			while (pagingHelper.MoveToNextPage())
			{
				yield return pagingHelper.GetCurrentPage().Select(FromInstance);
			}
		}

		private FilterElement<DomInstance> TranslateFullFilter(FilterElement<Template> filter)
		{
			if (filter is null)
			{
				throw new ArgumentNullException(nameof(filter));
			}

			FilterElement<DomInstance> translated;
			if (filter is ANDFilterElement<Template> and)
			{
				translated = new ANDFilterElement<DomInstance>(and.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is ORFilterElement<Template> or)
			{
				translated = new ORFilterElement<DomInstance>(or.subFilters.Select(TranslateFullFilter).ToArray());
			}
			else if (filter is NOTFilterElement<Template> not)
			{
				translated = new NOTFilterElement<DomInstance>(TranslateFullFilter(not.original));
			}
			else if (filter is TRUEFilterElement<Template>)
			{
				translated = new TRUEFilterElement<DomInstance>();
			}
			else if (filter is FALSEFilterElement<Template>)
			{
				translated = new FALSEFilterElement<DomInstance>();
			}
			else if (filter is ManagedFilterIdentifier managedFilter)
			{
				translated = TranslateFilter(managedFilter);
			}
			else
			{
				throw new NotSupportedException($"Unsupported filter: {filter}");
			}

			return translated;
		}

		private IOrderBy TranslateFullOrderBy(IOrderBy order)
		{
			if (order is null)
			{
				throw new ArgumentNullException(nameof(order));
			}

			var translatedElements = new List<IOrderByElement>();
			foreach (var orderByElement in order.Elements)
			{
				var translated = TranslateOrderBy(orderByElement);
				translatedElements.Add(translated);
			}

			return new OrderBy(translatedElements);
		}

		private FilterElement<DomInstance> TranslateFilter(ManagedFilterIdentifier managedFilter)
		{
			if (managedFilter is null)
			{
				throw new ArgumentNullException(nameof(managedFilter));
			}

			var fieldName = managedFilter.getFieldName().fieldName;
			var comparer = managedFilter.getComparer();
			var value = managedFilter.getValue();
			var translated = CreateFilter(fieldName, comparer, value);
			return translated;
		}

		private IOrderByElement TranslateOrderBy(IOrderByElement orderByElement)
		{
			if (orderByElement is null)
			{
				throw new ArgumentNullException(nameof(orderByElement));
			}

			var fieldName = orderByElement.Exposer.fieldName;
			var sortOrder = orderByElement.SortOrder;
			var naturalSort = orderByElement.Options.NaturalSort;
			var translated = CreateOrderBy(fieldName, sortOrder, naturalSort);
			return translated;
		}

		private Template FromInstance(DomInstance instance)
		{
			var obj = new Template
			{
				Identifier = instance.ID.Id.ToString()
			};
			var _templatepropertiesSection = instance.Sections.FirstOrDefault(s => s.SectionDefinitionID.Equals(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.SectionDefinitionId));
			if (_templatepropertiesSection != default)
			{
				var _name = _templatepropertiesSection.GetValue<string>(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.Name);
				if (_name != null)
				{
					obj.Name = _name.Value;
				}

				var _originsolution = _templatepropertiesSection.GetValue<string>(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.OriginSolution);
				if (_originsolution != null)
				{
					obj.OriginSolution = _originsolution.Value;
				}
			}

			return obj;
		}

		private DomInstance ToInstance(Template obj)
		{
			Guid id = default(Guid);
			if (!String.IsNullOrEmpty(obj.Identifier))
			{
				id = Guid.Parse(obj.Identifier);
			}
			else
			{
				id = Guid.NewGuid();
			}

			var instance = new DomInstance
			{
				DomDefinitionId = Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.DomDefinitionId,
				ID = new DomInstanceId(id)
				{
					ModuleId = Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.ModuleId
				}
			};
			var _templateproperties = new Section(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.SectionDefinitionId);
			if (obj.Name != default)
			{
				_templateproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.Name, Convert.ToString(obj.Name));
			}

			if (obj.OriginSolution != default)
			{
				_templateproperties.AddOrUpdateValue<string>(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.OriginSolution, Convert.ToString(obj.OriginSolution));
			}

			instance.Sections.Add(_templateproperties);
			return instance;
		}

		private FilterElement<DomInstance> CreateFilter(string fieldName, Comparer comparer, object value)
		{
			switch (fieldName)
			{
				case "Identifier":
					return FilterElementFactory.Create<DomInstance>(DomInstanceExposers.Id, comparer, Guid.Parse((string)value));
				case "Name" when (comparer is Comparer.Equals || comparer is Comparer.NotEquals) && value is null:
					return DomInstanceExposers.FieldValues.KeyExists(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.Name.Id.ToString()).Equal(comparer == Comparer.NotEquals);
				case "Name":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.Name), comparer, (string)value);
				case "OriginSolution" when (comparer is Comparer.Equals || comparer is Comparer.NotEquals) && value is null:
					return DomInstanceExposers.FieldValues.KeyExists(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.OriginSolution.Id.ToString()).Equal(comparer == Comparer.NotEquals);
				case "OriginSolution":
					return new DynamicManagedListFilter<DomInstance, object>(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.OriginSolution), comparer, (string)value);
				default:
					throw new NotImplementedException();
			}
		}

		private IOrderByElement CreateOrderBy(string fieldName, SortOrder sortOrder, bool naturalSort = false)
		{
			switch (fieldName)
			{
				case "Identifier":
					return OrderByElementFactory.Create(DomInstanceExposers.Id, sortOrder, naturalSort);
				case "Name":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.Name), sortOrder, naturalSort);
				case "OriginSolution":
					return OrderByElementFactory.Create(DomInstanceExposers.FieldValues.DomInstanceField(Skyline.DataMiner.Utils.ScheduledNotifications.Models.TemplateDomMapper.TemplateProperties.OriginSolution), sortOrder, naturalSort);
				default:
					throw new NotImplementedException();
			}
		}
	}
}