//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.ScheduledNotifications.Exposers
{
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Linq;
	using System.Runtime.CompilerServices;

	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.SDM;
	using Skyline.DataMiner.SDM.Exposers;

	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	public static partial class ScheduledNotificationExposers
	{
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string> Identifier = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string>((obj) => obj.Identifier, "Identifier");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string> UserEmail = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string>((obj) => obj.UserEmail, "UserEmail");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string> ItemId = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string>((obj) => obj.ItemId, "ItemId");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, Skyline.DataMiner.Utils.ScheduledNotifications.Models.NotificationType> NotificationType = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, Skyline.DataMiner.Utils.ScheduledNotifications.Models.NotificationType>((obj) => obj.NotificationType, "NotificationType");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string> OriginSolution = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, string>((obj) => obj.OriginSolution, "OriginSolution");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, bool> Status = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, bool>((obj) => obj.Status, "Status");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template>> TemplateId = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.ScheduledNotification, Skyline.DataMiner.SDM.SdmObjectReference<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template>>((obj) => obj.TemplateId, "TemplateId");
	}
}