//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGen package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.ScheduledNotifications.Exposers
{
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Linq;
	using System.Runtime.CompilerServices;

	using Skyline.DataMiner.Net.Messages.SLDataGateway;
	using Skyline.DataMiner.SDM;
	using Skyline.DataMiner.SDM.Exposers;

	using SLDataGateway.API.Querying;
	using SLDataGateway.API.Types.Querying;

	public static partial class TemplateExposers
	{
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string> Identifier = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string>((obj) => obj.Identifier, "Identifier");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string> Name = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string>((obj) => obj.Name, "Name");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string> DashboardFilePath = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string>((obj) => obj.DashboardFilePath, "DashboardFilePath");
		public static readonly Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string> OriginSolution = new Exposer<Skyline.DataMiner.Utils.ScheduledNotifications.Models.Template, string>((obj) => obj.OriginSolution, "OriginSolution");
	}
}